#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("RetailBeacon.Droid.Resource", IsApplication=true)]

namespace RetailBeacon.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aett = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int afyra = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bluetooth = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fgjsgjdjd = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int future_store_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int images = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int man = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int man2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menu = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sliderglass = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int trans = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int transbutton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int transuse = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int u49 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int u50 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int u53 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int u55 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int u68 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int wifi = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int button1 = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int fragment1 = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int help = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int mainWebView = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int new_game = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int spinner1 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dropdownItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragmenthome = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragmentinstoreinfo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragmentmyprofile = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int WebViewActivityLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int bottomMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
